### ISSUE TITLE
quote(unexistent_symbol) brings an error object not found

### ISSUE THREAD

**Issue by arnaud-feldmann** [r-wasm/quarto-live#37]
`quote(unexistent_symbol)` brings an error "object not found". Which shouldn't be the case as quote is supposed to be unevaluated.

Thanks for your work

**Comment by georgestagg** [comment]
Thank you for reporting this! I have reproduced and can confirm the bug.

I've made a change that should hopefully fix the problem, in commit [5df4c6a](https://github.com/r-wasm/quarto-live/commit/5df4c6a2aabf7036a3689679cccb98b4c958bdb6).

Please can you try updating the extension,

```
quarto update r-wasm/quarto-live
```

and let me know if that also fixes the problem for your documents?

**Comment by arnaud-feldmann** [comment]
Thanks. Seems like [it](https://github.com/arnaud-feldmann/formation_r_drieets_prog_fonctionnelle) works now. I've made the switch. Thanks
