### ISSUE TITLE
Support Altair HTML charts

### ISSUE THREAD

**Issue by joelostblom** [r-wasm/quarto-live#44]
When I run Altair code, I don't see any output, not even a textual representation of the chart. For example:

```py
import altair as alt

alt.Chart().mark_point()
```

![image](https://github.com/user-attachments/assets/08ac8448-1aed-462e-a8fd-298996680b37)

I also tried rendering the HTML via IPython display, but the following code gives the same empty output (html text renders fine in `HTML`):

```py
import altair as alt
from IPython.display import HTML

HTML(alt.Chart().mark_point().to_html())
```

I initially thought that this might be the same issue as https://github.com/coatless-quarto/pyodide/issues/7, but there a textual output is shown which indicates that altair detected that the frontend can't render the chart and doesn't produce the HTML version of the chart. In quarto-live, it seems like the HTML version of the chart is produced, but that something is interfering with displaying it. Is this the same issue as https://github.com/quarto-dev/quarto-cli/issues/3424? If so, is there anything that can be done from the altair-side of things to make support in quarto easier?

**Comment by joelostblom** [comment]
Given that it seems like plotly plots are also not working as per https://github.com/r-wasm/quarto-live/issues/47, I'm thinking what I reported here is a different issue than https://github.com/quarto-dev/quarto-cli/issues/3424, but it would be great to have some more insight here.

**Comment by georgestagg** [comment]
Yes, I think this is related to #47, but a distinct problem.

With some manual prodding in the JS console, I can get the plot to at least display - so it is possible this can work.

![Screenshot 2024-08-27 at 17 34 32](https://github.com/user-attachments/assets/c6f4c4af-d5b4-4017-9f1c-633835e41f34)

I'm going to deal with #47 first, as it will be required for this Issue too, then return here and continue to investigate.

**Comment by joelostblom** [comment]
Exciting! Thank you for looking into this!

**Comment by georgestagg** [comment]
As of e33a90038db8dc0780cb7ad946e1110a13b2d2d9 this should now work! I've added an example to the docs here:

https://r-wasm.github.io/quarto-live/other/py_output.html#example-altair-interactive-visualisation

I'm going to close this for now, but feel free to comment below if any particular features of Altair are broken and we can re-open to investigate :)

**Comment by joelostblom** [comment]
Wohoo! That's so great to see; thanks for the quick resolution!
