### ISSUE TITLE
If `format: revealjs` and there are `webr` cells on a slide, slide should be `scrollable` by default

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [r-wasm/quarto-live#67]
It's hard to predict how much space the output of a `webr` cell will be, so I'm finding myself adding the `{.scrollable}` class to every slide with a `webr` cell. And, of course, forgetting to do so every once in a while. It would be nice if the existence of a `webr` cell made the slide automatically scrollable. There may be reasons to not do this (either technical or not), but so far in my use-case, I can see it would be helpful.

**Comment by georgestagg** [comment]
Great idea, thanks!
