### ISSUE TITLE
gt example not working

### ISSUE THREAD

**Issue by mca91** [r-wasm/quarto-live#70]
The gt example in the "Interactive Tables" section of the documentation page (https://r-wasm.github.io/quarto-live/other/tables.html) is broken. The error reads

`wf: Error in `mount(mountpoint, data_url)`: Can't download Emscripten filesystem image metadata.`

**Comment by georgestagg** [comment]
Hi,

Sorry about that and thank your for reporting the issue! The problem with `gt` should now be resolved and the example up and running again.
