### ISSUE TITLE
Adding two newlines after a correct answer fails the grading step

### ISSUE THREAD

**Issue by rasmusab** [r-wasm/quarto-live#77]
Both when I've used `quarto-live` for myself, but also in the official examples, it seems like adding two or more newlines after a correct answer messes with the grading system somehow and results in the grading to fail what should be a correct answer.

See here for a screencast of this behavior using the first grading example at https://r-wasm.github.io/quarto-live/exercises/grading.html : 

https://github.com/user-attachments/assets/a1175344-cdef-4d20-abcb-a8800eefd040

I'm on:
* CHROME VERSION - 130.0.6723.117
* OS VERSION - Mac OS X: 15.1.0

_Update_: Also, I should have been clear with that, from what I can see, this only happens on the R-version of `quarto-live`.

**Comment by georgestagg** [comment]
Thank you for reporting this!

It seems to be a consequence of using the {evaluate} package to run user supplied R code. The trailing newlines are interpreted and retained by `evaluate::evaluate()`.

Commit f2afcbecb8eac84f5c770a51a4f780d74ceb9222 should work around the issue to collapsing multiple trailing newlines into a single newline in user submitted R code.
